### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Zi7ar21** [Battelle/cantordust#1]
Hello, I have followed the directions in `readme.md`. I took the following steps in order:
- Downloaded [Gihdra](https://ghidra-sre.org/) [v9.1.2](https://ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip)
- Extracted it and ran `/ghidra_9.1.2_PUBLIC/ghidraRun.bat`
- It returned error (needed JDK)
- Installed JDK
- Ran `/ghidra_9.1.2_PUBLIC/ghidraRun.bat`
- Clicked through
- Gihdra GUI popped up
- Troubleshooted and found the green play button was actually only visible after clicking the dragon (CodeBrowser)
- Pressing the Green Play Button (Display Script Manager)
- Pressing Script Directories
- Downloaded the `.zip` copy of this repository
- Extracted it as `C:\cantordust-master`
- Added it to the script directories in Gihdra
- Selected `Cantordust.java` from the list
- Pressed the green play button (Run Script)
- It returned:
```Error running script: Cantordust.java
java.lang.NullPointerException: null
java.lang.NullPointerException
	at Cantordust.run(Cantordust.java:38)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-14.0.2
JVM Version: Oracle Corporation 14.0.2
OS: Windows 10 10.0 amd64
Workstation: Adam-HP
```
- Retried with cloning the repository to `C:\cantordust` and same error

I am new to this kind of stuff, and frankly I just want this in a nice executable package without all the Gihdra hassle. I heard of Cantor Dust a while ago, the whole idea has been super epic to me. Glad to see the full version finally available. Hope we can get this working. Cheers!

By the way mention the CodeBrowser and the dragon in the readme steps it really helps

**Comment by Amccanty** [comment]
Hi Zi7zar21,

I'll try to take a look at what's going on. Did you load a file you wanted to examine with CantorDust into ghidra? If so could you share that file?

Have you tried running the CantorDust script on multiple files and gotten the same result?

**Comment by cetfor** [comment]
Hey @Zi7ar21 - it looks like this happens because you don't have a loaded binary target.

`Cantordust.run(Cantordust.java:38)` points to [this line in the code](https://github.com/Battelle/cantordust/blob/master/Cantordust.java#L38):
`name = currentProgram.getName();`

It's throwing the exception because it needs to resolve a `currentProgram` object which isn't yet populated.  Throw a binary into Ghidra, then press the green play button and you should be good.

This should be filed as a bug and handled. Good catch. ;)

**Comment by Zi7ar21** [comment]
wait this is because I didn't open a file
LOL I am silly thank you

**Comment by Battelle-Cyber-34** [comment]
Should be fixed in latest merge.
